version: '3.8'

services:
  cortex_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /Volumes:/Volumes
      - /Users/user/RANTUNES:/Volumes/RANTUNES
      - .:/app
      - backend_node_modules:/app/node_modules
    restart: always
    networks:
      - default
      - supabase

  cortex_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4029:4029"
    env_file:
      - .env
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - cortex_backend
    restart: always
    networks:
      - default

  cortex_worker:
    build:
      context: .
      # If you have a specific dockerfile for the worker, e.g. Dockerfile.worker
      # but assuming it runs node from the repository
      dockerfile: Dockerfile.backend
    command: [ "node", "worker/dispatcher.js" ]
    env_file:
      - .env
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - cortex_backend
    restart: always
    networks:
      - default
      - supabase

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate.yml:/config/config.yml
      - ./frigate_storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5050:5000"
      - "8554:8554"
      - "8555:8555"
    networks:
      - default
    devices:
      - /dev/video0:/dev/video0 # Map USB Camera

networks:
  default:
    name: frontend_source_default
  supabase:
    external: true
    name: supabase_network_iCaffeOS

volumes:
  backend_node_modules:
  frontend_node_modules:
